### ISSUE TITLE
grafi

### ISSUE THREAD

**Issue by maxfilip98** [maxfilip98/APPR-2017-18#2]
Spoštovani, imam nekaj vprašanj glede mojega programa. Pri risanju zemljevida  BDP (graf.BDP) mi obarva vse države razen Nemčije in ne najdem zakaj. Prav tako mi pri grafu graf.rastBDP_Nem grafa sploh ne pokaže, a ne vrne nobene napake ko program poženem.
Pri grafu BDP2016 se iz grafa ne uspem znebiti Evropske unije, kar sam poizkusil naresti v filtru. Zanima me pa še kako bi lahko na en graf narisal dve funkciji in ukaz za pie chart.
Najlepša hvala.

**Comment by jaanos** [comment]
Problem je v tem, da imaš za Nemčijo v razpredelnici `BDP` niz `"Germany "` - torej s presledkom na koncu. Najlažje bo, če ga pobrišeš ob brisanju oklepajev na koncu. Obenem se lahko znebiš agregatnih podatkov za Evropsko unijo oziroma evroobmočje:
```R
BDP <- filter(BDP, leta >= 1999, ! grepl("^Euro", drzava))
BDP$drzava <- gsub(" \\([^)]*\\)", "", BDP$drzava)
```
Iz regularnega izraza sem odstranil odvečne oklepaje, saj si ti ni potrebno zapomniti najdenih nizov.

Pri risanju zemljevida se ti levo spodaj izriše Francoska Gvajana. Da izrišeš samo Evropo, lahko s `coord_cartesian` podaš omejitve koordinat. Poleg tega se na lestvici znebi eksponentnega zapisa - BDP podaj v milijonih evrov, npr.
```R
graf.BDP <- ggplot() + 
  geom_polygon(data = left_join(zemljevid,
                                BDP %>% filter(leta==2016,
                                               sestava=="Gross domestic product at market prices"),
                                by = c("NAME_LONG" = "drzava")),
               aes(x = long, y = lat, group = group, fill = vrednost/1000000)) +
  ggtitle("BDP 2016") + xlab("") + ylab("") +
  guides(fill = guide_colorbar(title = "BDP v milijonih eur")) +
  coord_cartesian(xlim = c(-25, 40), ylim = c(32, 72))
```

Z zgornjim filtriranjem se sedaj znebiš podatkov za Evropsko unijo. Svetujem, da države urediš po prikazani vrednosti - v ta namen lahko uporabiš funkcijo `reorder`, ki ji podaš še vrednosti, po katerih urejaš. Za boljšo berljivost lahko imena držav zarotiraš. Za barvanje ploskev (kot so stolpci) namesto `color` (ki določi barvo roba) uporabi `fill`.
```R
graf.BDP2016 <- ggplot(BDP %>% filter(leta == 2016,
                                      sestava == "Gross domestic product at market prices"),
                           aes(x = reorder(drzava, -vrednost), y = vrednost/1000000)) +
  geom_col(fill = "green") + xlab("Država") + ylab("milijoni evrov") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

Če želiš prikazati več grafov skupaj, morajo podatki biti v isti razpredelnici (v istem stolpcu - torej na isti skali). Potem lahko prikazane podatke glede na tip ločiš npr. z barvami:
```R
graf.obrestne <- ggplot(obrestne_mere, aes(x = datum, y = vrednost, color = vrsta)) + geom_line()
```

Tortni diagram se z `ggplot2` naredi kot stolpčni diagram z enim razdeljenim stolpcem (širine 1, da ne bo na sredini luknje), ki ga prikažemo na polarnem koordinatnem sistemu. Če bi želel prikazati razdelitev BDP, bi šlo nekako tako:
```R
podatki <- BDP %>% filter(leta == 2016, sestava == "Gross domestic product at market prices") %>%
  arrange(desc(vrednost)) %>% mutate(drzava = ifelse(row_number() > 10, "Ostale", drzava)) %>%
  group_by(drzava) %>% summarise(vrednost = sum(vrednost, na.rm = TRUE))

ggplot(podatki, aes(x = factor(1), y = vrednost/1000000,
                    fill = reorder(drzava, ifelse(drzava == "Ostale", 0, vrednost)))) +
  geom_col(width = 1) + coord_polar(theta = "y") + xlab("") + ylab("") +
  guides(fill = guide_legend("Država", reverse = TRUE)) + ggtitle("BDP v milijonih evrov") +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
```
Ker bi bilo držav preveč za prikaz na enem diagramu, zgoraj pripravljeni podatki prikažejo samo prvih 10 držav, za ostale pa se seštejejo vrednosti. Države nato razporedimo po prikazani vrednosti, pri čemer poskrbimo, da združene države prikažemo na koncu (pravzaprav na vrhu stolpca). Pri legendi je potrebno vrstni red še obrniti, da bo država z največjim BDP na vrhu.

**Comment by maxfilip98** [comment]
Ko sem popravil prve stvari, ki ste mi jih napisali Nemčije še zmeraj ni pobarvalo in zemljevid ostane nespremenjen. Pri grafu graf.BDP pa mi napiše error unexpected INCOMPLETE_STRING v vrstici 30. 
Najlepša hvala še enkrat za pomoč.

**Comment by jaanos** [comment]
Mišljeno je bilo, da zgornji vrstici uporabiš namesto vrstic 34 in 35 v `uvoz.r`. Popravi tudi sledečo vrstico - naj bo vse v eni vrstici (torej brez preloma vrstice pred `"`), da se popravi tudi ime za Makedonijo.

Mimogrede: podatke imaš tudi za Turčijo in Ciper, tako da ju vključi v zemljevid (tam je kot celina navedena Azija).

**Comment by maxfilip98** [comment]
Sedaj sem popravil,  zgoraj omenjene napake in dodal še nekaj grafov, ki ste jih predlagali. Me pa samo še zanima kako lahko z ukazom coord_cartesian dodam še Turčijo in Ciper. Prav tako bi samo še vprašal zakaj mi javi v grafu graf.BDP2016 napako, samo če poženem celoten program, če pa poženem vrstice eno in po eno z "run" pa vse dela normalno. Ali bom ko odpravim ti dve napaki, končal s tretjo fazo, ali bo potrebno narediti še kaj?
Najlepša hvala

**Comment by jaanos** [comment]
S `coord_cartesian` lahko samo določiš meje, v katerih se bo graf izrisal. Če želiš vključiti še Turčijo in Ciper (pravzaprav bo treba vključiti tudi Severni Ciper), to storiš pri filtriranju zemljevida:
```R
zemljevid <- zemljevid %>% filter (CONTINENT %in% c("Europe") |
                                     NAME_LONG %in% c("Turkey", "Cyprus", "Northern Cyprus"),
                                   NAME_LONG != "Russian Federation")
```

Pri meni `graf.BDP2016` deluje, ko poženem `vizualizacija.r` (pa tudi, če poženem vrstico samo). Kakšno napako pa dobiš? Jaz dobim samo opozorilo, da združuješ faktor in znakovni vektor.

Da boš pripravljen za predstavitve naslednji teden, še uredi poročilo - po tem, ko kličeš `vizualizacija.r`, lahko izrišeš pripravljene grafe in za vsakega podaš kratko interpretacijo. Primer risanja zemljevida že imaš v poročilu - ker imaš grafe že definirane v `vizualizacija.r`, lahko kodo enostavno nadomestiš s spremenljivko, kjer imaš želeni graf. Del, ki ga še ne potrebuješ (razdelek *Napredna analiza podatkov*) pobriši, da se ti bo poročilo prevedlo. Svetujem tudi, da odstraniš vrstico `runtime: shiny` iz glave poročila - namesto gumba *Run Document* se bo pojavil gumb *Knit*, s katerim prevedeš poročilo v obliko HTML.

**Comment by maxfilip98** [comment]
Dodal sem ukaz v zemljevid, a mi še zmeraj ne pokaže Cipra in Turčije, ali je možno, da je to zaradi ukaza coord cortesian. 
Program pa mi vrne naslednjo napako, o kateri sem vam pisal malo časa nazaj:
Error in source("~/Documents/fim 2. letnik/programeranje R/APPR-2017-18/vizualizacija/vizualizacija.r",  : 
  ~/Documents/fim 2. letnik/programeranje R/APPR-2017-18/vizualizacija/vizualizacija.r:30:35: unexpected INCOMPLETE_STRING
29:                        aes(x = reorder(drzava, -vrednost), y = vrednost/1000000)) +
30:   geom_col(fill = "green") + xlab("Dr
                                      ^
In addition: Warning message:
In readLines(file, warn = FALSE) :
  invalid input found on input connection '~/Documents/fim 2. letnik/programeranje R/APPR-2017-18/vizualizacija/vizualizacija.r'

**Comment by jaanos** [comment]
Na katerem zemljevidu ti ne prikaže Cipra in Turčije? Meni ju prikaže tako na `graf.BDP` in `graf.inflacija` (Severni Ciper je seveda siv, ker zanj nimaš podatkov). Morda bo pomagalo, če pri uvozu zemljevida funkciji `uvozi.zemljevid` dodaš še parameter `encoding = ""` (tako se ne bo izvedla pretvorba podatkov v kodiranje UTF-8).

Napaka, ki jo dobiš, pa izgleda, kot da ima RStudio težave s šumniki. Kdaj pa dobiš napako - ko klikneš na *Source*, ali ko prevajaš poročilo? Lahko poskusiš pognati program z ukazom `source`, tako kot v poročilu - poskusi tako s parametrom `encoding` kot brez, in v poročilu uporabljaj tisto različico, ki deluje (če sploh katera):
```R
source("vizualizacija/vizualizacija.r", encoding = "UTF-8")
```

Mimogrede, opažam, da si pred vsebino na koncu poročila postavil procente. Ti žal ne delujejo kot komentar v RMarkdownu, zato to vsebino raje odstrani, da se ti bo poročilo prevedlo in bo lepo izgledalo.

**Comment by maxfilip98** [comment]
Sedaj zemljevida tudi pri meni delujeta, ko sem zaprl in odprl program in dodal encoding.

Napako mi javi vedno ko poženem s source-om. Zaradi te napake tudi vedno ko poženem run document v projekt.Rmd mi vrne sam prazen list na katerem je napisana napaka.

Drugače pa sem sedaj posodobil tudi projekt.Rmd, v katerega moram le še vnesti grafe (do sedaj sem le določil pozicije).

**Comment by jaanos** [comment]
Če imaš čas, predlagam, da se jutri zglasiš ob 12h v kabinetu 5.14 s svojim računalnikom, pa pogledava, kaj se da storiti glede kodiranja znakov.

Sicer pa, če želiš v poročilu izrisati graf (ali izvajati kakršnokoli drugo R-jevo kodo), bo treba to storiti v ustreznem bloku kode, npr.
```R
    ```{r graf.BDP, echo=FALSE, message=FALSE, fig.align='center', fig.cap='Graf BDP'}
    graf.BDP
    ```
```
(brez začetnega zamika). Pazi na ustrezno poimenovanje spremenljivk - te so občutljive za velikost črk.

Še to: Markdown načeloma zazna hiperpovezave, a včasih ne zazna pravilno, kdaj se te končajo. Zato bo bolje, če jih eksplicitno podaš - bodisi postaviš URL med `<>`, pa ga bo prikazalo kot hiperpovezavo, ali pa med `[]` postaviš želeno besedilo in takoj za tem med `()` še URL. Da bo lepše izgledalo, povezave lahko našteješ v seznamu, npr.
```markdown
* [Podatki z Eurostata](http://appsso.eurostat.ec.europa.eu/nui/show.do?query=BOOKMARK_DS-406763_QID_-7AA5FD9F_UID_-3F171EB0&layout=TIME,C,X,0;NA_ITEM,L,Y,0;GEO,L,Y,1;UNIT,L,Z,0;INDICATORS,C,Z,1;&zSelection=DS-406763UNIT,CLV10_MEUR;DS-406763INDICATORS,OBS_FLAG;&rankName1=UNIT_1_2_-1_2&rankName2=INDICATORS_1_2_-1_2&rankName3=TIME_1_0_0_0&rankName4=NA-ITEM_1_0_0_1&rankName5=GEO_1_0_1_1&sortR=ASC_-1_FIRST&sortC=ASC_-1_FIRST&rStp=&cStp=&rDCh=&cDCh=&rDM=true&cDM=true&footnes=false&empty=false&wai=false&time_mode=NONE&time_most_recent=false&lang=EN&cfo=%23%23%23%2C%23%23%23.%23%23%23)
* <https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html>
* http://ec.europa.eu/eurostat/tgm/table.do?tab=table&init=1&language=en&pcode=tec00118&plugin=1
```
Za seznamom pusti prazno vrstico, sicer se bo nadaljevala zadnja točka seznama. Prav tako naj bo pred seznamom prazna vrstica.

Na koncu kličeš še gradnik Shiny, ki pa je še iz vzorca - najbolje bo, da zaenkrat izbrišeš celoten razdelek *Napredna analiza podatkov*.

**Comment by maxfilip98** [comment]
Ali bi lahko prišel ob 11h?

**Comment by jaanos** [comment]
Lahko prideš ob 11h.
